name: Notes from a Messy Desk

pygments: true

assets:
  compress:
    css: sass
    js:  uglifier

permalink: /:title/

# Only show a maximum of 4 posts in a page. Works reasonably well so far with
# the volume of posts I produce these days.
paginate: 4

exclude:
  - Gemfile*
